// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QivAlQDtBltQcEsVt9R3EFz5loxKrKA',
    appId: '1:239650923783:web:e2cc3b465f53a096e111a2',
    messagingSenderId: '239650923783',
    projectId: 'anime-vault-2ae90',
    authDomain: 'anime-vault-2ae90.firebaseapp.com',
    storageBucket: 'anime-vault-2ae90.appspot.com',
    measurementId: 'G-F6ZD5E6NNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUF3Rh_N7p9pMhge4BT2O02NqWqWh_o0',
    appId: '1:239650923783:android:61b93f70530d5168e111a2',
    messagingSenderId: '239650923783',
    projectId: 'anime-vault-2ae90',
    storageBucket: 'anime-vault-2ae90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMH_2AX6OqFPXMy3KSV3MkZi0NVXPvb0',
    appId: '1:239650923783:ios:d9b786cfa1be4aeee111a2',
    messagingSenderId: '239650923783',
    projectId: 'anime-vault-2ae90',
    storageBucket: 'anime-vault-2ae90.appspot.com',
    iosClientId: '239650923783-dv2i5maurmhk7fb92smlg2iph60l7k0u.apps.googleusercontent.com',
    iosBundleId: 'com.devcae.animeVault',
  );
}
